-- Detection Engineering: SQL-based Threat Hunting (SIEM approach)
--
-- This legacy aggregate file is kept as a convenience index.
-- The source of truth is now detection-as-code under:
--
--   secops/security-data-lake/detections/*/
--
-- Each detection folder contains README.md, metadata.yaml, query.sql,
-- sample-events.json, and expected-result.json.
